name: Deploy to EC2

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up SSH agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS }}

      # 3. Deploy using SCP
      - name: Deploy to EC2
        run: |
          scp-r -o StrictHostKeyChecking=no . ec2-user@ec2-13-48-67-79.eu-north-1.compute.amazonaws.com:/home/ec2-user/connect-four-reboot/
